# Generated by Django 5.0.4 on 2024-04-22 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('itemType', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('trinket', 'Trinket')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_damage', models.FloatField(default=0)),
                ('magic_damage', models.FloatField(default=0)),
                ('critical_damage', models.FloatField(default=200)),
                ('critical_chance', models.FloatField(default=0)),
                ('strength', models.FloatField(default=4)),
                ('intelligence', models.FloatField(default=4)),
                ('dexterity', models.FloatField(default=4)),
                ('focus', models.FloatField(default=4)),
                ('strength_modifier', models.FloatField(default=100)),
                ('intelligence_modifier', models.FloatField(default=100)),
                ('dexterity_modifier', models.FloatField(default=100)),
                ('focus_modifier', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.itemtemplate')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.ManyToManyField(related_name='owned_by', to='rpg.playeritem'),
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='rpg.itemtemplate')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rpg.shop')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.statsheet'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.statsheet'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currency', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='rpg.vendor'),
        ),
    ]
